// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmgxxAhxjYmYgj5z8amHBIuRk-Tn076ds',
    appId: '1:698502312073:web:f3e457f28f05af004d9658',
    messagingSenderId: '698502312073',
    projectId: 'spendeconnect-ac211',
    authDomain: 'spendeconnect-ac211.firebaseapp.com',
    storageBucket: 'spendeconnect-ac211.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXAAgdCtL8-Gl4eK8v7fZJHpHxyIT9M0U',
    appId: '1:698502312073:android:829fd6ec0f72539b4d9658',
    messagingSenderId: '698502312073',
    projectId: 'spendeconnect-ac211',
    storageBucket: 'spendeconnect-ac211.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHeyrqFnGyMpO4LbOAsOn61-9jRagWYho',
    appId: '1:698502312073:ios:511c348d718382c04d9658',
    messagingSenderId: '698502312073',
    projectId: 'spendeconnect-ac211',
    storageBucket: 'spendeconnect-ac211.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHeyrqFnGyMpO4LbOAsOn61-9jRagWYho',
    appId: '1:698502312073:ios:7985d82135f36d5e4d9658',
    messagingSenderId: '698502312073',
    projectId: 'spendeconnect-ac211',
    storageBucket: 'spendeconnect-ac211.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
