// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMpFeQCWbYDU6Pay0KpX9MaQKG_m3hu3I',
    appId: '1:819684240828:web:bd830dddeb9096ac760fb9',
    messagingSenderId: '819684240828',
    projectId: 'spendeconnect',
    authDomain: 'spendeconnect.firebaseapp.com',
    storageBucket: 'spendeconnect.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGYZ_mQucVImYxElKfcr-ppzLz5OpAmoA',
    appId: '1:819684240828:android:4eb14bb9fc3c4ae1760fb9',
    messagingSenderId: '819684240828',
    projectId: 'spendeconnect',
    storageBucket: 'spendeconnect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoy7rj-HTjChze_lVzpB2N68RpwOZC3-8',
    appId: '1:819684240828:ios:ce838e3fe544e863760fb9',
    messagingSenderId: '819684240828',
    projectId: 'spendeconnect',
    storageBucket: 'spendeconnect.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoy7rj-HTjChze_lVzpB2N68RpwOZC3-8',
    appId: '1:819684240828:ios:80abc399b1dcd652760fb9',
    messagingSenderId: '819684240828',
    projectId: 'spendeconnect',
    storageBucket: 'spendeconnect.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
